[package]
name = 'r-phylo2vec'
version = '0.1.0'
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true

[lib]
crate-type = [ 'staticlib' ]
name = 'phylo2vec'

[dependencies]
extendr-api = '0.7.1'
phylo2vec = { workspace = true }
